### ISSUE TITLE
Build Failing on OSX

### ISSUE THREAD

**Issue by jordonbiondo** [p-org/P#96]
Following the wiki instructions for building P with build.sh on OSX failed on my machine.

I first received this permissions denied error when trying to execute `SetupVsBinaries.cmd` in the FormulaCodeGeneratoryTask project because it doesn't have executable permissions, but this isn't the real issue. The real issue is that the build is trying to execute `SetupVsBinaries.cmd` as a shell command on my OSX machine which obviously won't work.

I was able to get the build to finish by: 

1. Adding executable permissions to the file.
2. Replacing the contents of `SetupVsBinaries.cmd` with the equivalent  `bash` script.

Clearly this isn't the correct cross-platform solution, and I don't know enough about the `.sln` world to propose one, but the cmd file as is not working.

**Comment by henesy** [comment]
What was the script that you replaced the .cmd with? I'm running into the same issue on Ubuntu Linux where the build fails on the same file.

**Comment by desaiankush** [comment]
There was a recent change in Formula:
https://github.com/Microsoft/formula/commit/a7dd07057a99f792a99a67c87a2a7708a16a1c7b

And we didn't update the Linux build corresponding to it.
Will fix this in sometime. Thanks for pointing out.

**Comment by clovett** [comment]
Yeah, but that change is only important if you are running Visual Studio at the same time as building those bits...

**Comment by desaiankush** [comment]
Yeah, so I guess the solution would be to ignore this cmd for linux/OSX and do it only for windows platform?

**Comment by lovettchris** [comment]
Right.

**Comment by desaiankush** [comment]
@clovett Can you fix the formula repo ?

**Comment by thisiscam** [comment]
Ignoring the call to the cmd file does not work.  I got the message below:
`/Users/jianqiaoyang/Desktop/p-org/P5/Ext/Formula/Src/Extensions/FormulaCodeGeneratorTask/FormulaCodeGeneratorTask.Targets: error : ### Please build /Users/jianqiaoyang/Desktop/p-org/P5/Ext/Formula/Src/Extensions/FormulaCodeGeneratorTask//Debug/x86/vs/FormulaCodeGeneratorTask.dll`

**Comment by clovett** [comment]
I'm working on a fix...

**Comment by clovett** [comment]
This should be fixed now.  I'm having other problems building on Unix, I get an error saying : **error** : Error initializing task Error: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.  So I have not been able to test my fix on Unix.

**Comment by thisiscam** [comment]
The build succeeds now on my macOS, but still fails on Ubuntu 14.04, with the same message
`/home/user/Desktop/P5/Ext/Formula/Src/Extensions/FormulaCodeGeneratorTask/FormulaCodeGeneratorTask.Targets: error : ### Please build /home/user/Desktop/P5/Ext/Formula/Src/Extensions/FormulaCodeGeneratorTask//Debug/x86/FormulaCodeGeneratorTask.dll
` 

@clovett for debugging the message you are seeing, which mono version are you using?

**Comment by lovettchris** [comment]
This one is interesting, you do need to build Debug/x86/FormulaCodeGeneratorTask.dll in order for the build to succeed. Since this is a build task.

Does xbuild support custom build tasks?

**Comment by thisiscam** [comment]
After some investigation, the problem lies on the sensitivity of path in unix system. The MONO_IOMAP variable seems to hitting on an edge case that's causing it to not function properly. Notice the message below:
`error : ### Please build /home/user/Desktop/P5/Ext/Formula/Src/Extensions/FormulaCodeGeneratorTask//Debug/x86/FormulaCodeGeneratorTask.dll
`
It has two slashes before "Debug", also not it's upper cased D.

And on this change: https://github.com/Microsoft/formula/blob/a7dd07057a99f792a99a67c87a2a7708a16a1c7b/Src/Extensions/FormulaCodeGeneratorTask/FormulaCodeGeneratorTask.csproj#L17

we have "debug/x86"

I do not know exactly why this happens but it's the case that I can either:
1. remove one slash
2. change to the correct case, instead of relying on MONO_IOMAP
to make the build succeeds on Ubuntu. 

This issue didn't happen on Mac because macOS is "halfly case sensitive" and thus maybe it was able to dodge the corner case bug in MONO_IOMAP.  Though this is purely speculation.

To fix the issue, either remove the redundant slash, or correct "debug"/"release" -> $(Configuration)

**Comment by jordonbiondo** [comment]
@clovett A clean run of `./build.sh` now succeeds on my machine, thank you.

**Comment by clovett** [comment]
Fixed.  This [commit](https://github.com/p-org/P/commit/356502fb46d700e84091313275cfd0a0bc97850a) pulls fix from [Formula git submodule](https://github.com/Microsoft/formula/commit/5d9850e417a628761963e019d50c5a1b62d384bc).
